[versions]
android-plugin = "9.0.0"
kotlin-plugin = "2.3.0"
google-ksp-plugin = "2.3.5"
maven-publish-plugin = "0.36.0"

androidx-junit = "1.3.0"
androidx-espresso = "3.7.0"
androidx-appcompat = "1.7.1"
androidx-activity = "1.12.3"
androidx-room = "2.8.4"
androidx-compose-bom = "2026.01.01"
androidx-compose-paging = "3.4.0"

junit = "4.13.2"

google-gson = "2.13.2"
google-material = "1.13.0"

squareup-okHttp = "5.3.2"
squareup-retrofit = "3.0.0"

monitor = "1.8.5"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }

androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish-plugin" }

[libraries]
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-compose-paging" }

junit = { module = "junit:junit", version.ref = "junit" }

google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }

squareup-okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareup-okHttp" }
squareup-okHttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "squareup-okHttp" }

squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareup-retrofit" }
squareup-retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "squareup-retrofit" }

monitor = { module = "io.github.leavesczy:monitor", version.ref = "monitor" }
monitor-no-op = { module = "io.github.leavesczy:monitor-no-op", version.ref = "monitor" }